# GoReleaser config
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: lt
    main: ./cmd/lt
    binary: lt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/adammpkins/llamaterm/internal/cli.Version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'

release:
  github:
    owner: adammpkins
    name: llama-terminal-completion
  draft: false
  prerelease: auto
